{% set name = "aws-cdk.region-info" %}
{% set version = "2.139.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/aws-cdk.region-info-{{ version }}.tar.gz
  sha256: e97e936787856fe65e24247c374c9fff0b65e32c9d528ebd858e250241fcf6ce

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - setuptools >=67.3.2,<67.4.dev0
    - wheel >=0.40,<1.dev0
    - pip
  run:
    - python >=3.7
    - python-jsii >=1.97.0,<2.0.0
    - publication >=0.0.3
    - typeguard >=2.13.3,<2.14.dev0

test:
  imports:
    - aws_cdk.region_info
    - aws_cdk.region_info._jsii
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/aws/aws-cdk
  summary: AWS region information, such as service principal names
  dev_url: https://github.com/aws/aws-cdk
  license: Apache-2.0
  license_file:
    - NOTICE
    - LICENSE

extra:
  recipe-maintainers:
    - ocefpaf
