{% set python_min = "3.8" %}
{% set name = "aws-cdk.region-info" %}
{% set version = "2.173.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/aws_cdk_region_info-{{ version }}.tar.gz
  sha256: 7991b4183dd008394d25e790aa9b0d81c7d32c81470da0b4f5cc2664789f40bc

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=67.3.2,<67.4.dev0
    - wheel >=0.40,<1.dev0
    - pip
  run:
    - python >={{ python_min }}
    - python-jsii >=1.104.0,<2.0.0
    - publication >=0.0.3
    - typeguard >=2.13.3,<4.3.0

test:
  imports:
    - aws_cdk.region_info
    - aws_cdk.region_info._jsii
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/aws/aws-cdk
  summary: AWS region information, such as service principal names
  dev_url: https://github.com/aws/aws-cdk
  license: Apache-2.0
  license_file:
    - NOTICE
    - LICENSE

extra:
  recipe-maintainers:
    - ocefpaf
