{% set name = "aws-cdk.region-info" %}
{% set version = "2.184.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/aws_cdk_region_info-{{ version }}.tar.gz
  sha256: 4f840d5ba585dda9a2a51fc806a1fb668db08180bb57c4384a125f0814d7fbf1

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=67.3.2,<67.4.dev0
    - wheel >=0.40,<1.dev0
    - pip
  run:
    - python >={{ python_min }}
    - python-jsii >=1.109.0,<2.0.0
    - publication >=0.0.3
    - typeguard >=2.13.3,<4.3.0

test:
  imports:
    - aws_cdk.region_info
    - aws_cdk.region_info._jsii
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/aws/aws-cdk
  summary: AWS region information, such as service principal names
  dev_url: https://github.com/aws/aws-cdk
  license: Apache-2.0
  license_file:
    - NOTICE
    - LICENSE

extra:
  recipe-maintainers:
    - ocefpaf
